sudo: false
language: node_js
node_js:
- 8.9.0
addons:
  ssh_known_hosts:
    - 139.224.12.199 #受信主机，你的Linux服务器ip
branchs:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_a06631ba4bb8_key -iv $encrypted_a06631ba4bb8_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - logname
  - ifconfig
install:
  - cd demo && npm install
script:
  - npm start
after_success:
  - ssh travis@139.224.12.199 -o StrictHostKeyChecking=no 'cd ~/egg && git pull && chmod 755 build.sh && ./build.sh'   #使用ssh连接服务器
