sudo: false
language: node_js
node_js:
- 8.9.0
install:
- docker build -t egg-demo .
- docker stop egg-demo-s && docker rm egg-demo-s
- docker run -d -p 80:7001 --name egg-demo-s egg-demo
before_install:
- openssl aes-256-cbc -K $encrypted_a06631ba4bb8_key -iv $encrypted_a06631ba4bb8_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
