sudo: false
language: node_js
node_js:
- 8.9.0
addons:
  ssh_known_hosts:
  - 139.224.12.199
branchs:
  only:
  - master
install:
- cd demo && npm install
script:
- npm run ci
after_script:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@139.224.12.199 -o StrictHostKeyChecking=no 'cd ~/egg-damo/egg/ && git pull && chmod
  755 build.sh && ./build.sh'
before_install:
- openssl aes-256-cbc -K $encrypted_7b97b7138bdd_key -iv $encrypted_7b97b7138bdd_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
